import type { Task } from "./types";

export const tasks: Task[] = [
  {
    id: "1",
    name: "Remove Catalytic Converter",
    type: "Mechanical",
    laborCost: 75,
    linkedVehiclesCount: 32,
  },
  {
    id: "2",
    name: "Install Catalytic Converter",
    type: "Mechanical",
    laborCost: 80,
    linkedVehiclesCount: 32,
  },
  {
    id: "3",
    name: "Recycle Catalytic Powder",
    type: "Refine",
    laborCost: 100,
    linkedVehiclesCount: null,
  },
  {
    id: "4",
    name: "Repair Exhaust Pipe",
    type: "Mechanical",
    laborCost: 60,
    linkedVehiclesCount: 46,
  },
  {
    id: "5",
    name: "Diagnose Check Engine Light",
    type: "Inspection",
    laborCost: 45,
    linkedVehiclesCount: null,
  },
  {
    id: "6",
    name: "Inspect Emissions System",
    type: "Inspection",
    laborCost: 45,
    linkedVehiclesCount: null,
  },
  {
    id: "7",
    name: "Replace Exhaust Manifold",
    type: "Mechanical",
    laborCost: 99,
    linkedVehiclesCount: 14,
  },
  {
    id: "8",
    name: "Decan Ceramic Substrate",
    type: "Refine",
    laborCost: 120,
    linkedVehiclesCount: null,
  },
  {
    id: "9",
    name: "Weld Exhaust Flange",
    type: "Mechanical",
    laborCost: 55,
    linkedVehiclesCount: 22,
  },
  {
    id: "10",
    name: "Oxygen Sensor Replacement",
    type: "Mechanical",
    laborCost: 40,
    linkedVehiclesCount: 88,
  },
  {
    id: "11",
    name: "Muffler Installation",
    type: "Mechanical",
    laborCost: 70,
    linkedVehiclesCount: 54,
  },
  {
    id: "12",
    name: "Emission Control Calibration",
    type: "Inspection",
    laborCost: 90,
    linkedVehiclesCount: 12,
  },
  {
    id: "13",
    name: "Precious Metal Assaying",
    type: "Refine",
    laborCost: 250,
    linkedVehiclesCount: null,
  },
  {
    id: "14",
    name: "DPF Cleaning Service",
    type: "Mechanical",
    laborCost: 150,
    linkedVehiclesCount: 19,
  },
  {
    id: "15",
    name: "Visual Pipe Inspection",
    type: "Inspection",
    laborCost: 30,
    linkedVehiclesCount: null,
  },
  {
    id: "16",
    name: "Resonator Removal",
    type: "Mechanical",
    laborCost: 65,
    linkedVehiclesCount: 11,
  },
  {
    id: "17",
    name: "Grinding Ceramic Monolith",
    type: "Refine",
    laborCost: 85,
    linkedVehiclesCount: null,
  },
  {
    id: "18",
    name: "Tailpipe Alignment",
    type: "Mechanical",
    laborCost: 35,
    linkedVehiclesCount: 42,
  },
  {
    id: "19",
    name: "Smoke Leak Test",
    type: "Inspection",
    laborCost: 50,
    linkedVehiclesCount: null,
  },
  {
    id: "20",
    name: "Turbocharger Linkage Repair",
    type: "Mechanical",
    laborCost: 180,
    linkedVehiclesCount: 7,
  },
  {
    id: "21",
    name: "EGR Valve Cleaning",
    type: "Mechanical",
    laborCost: 110,
    linkedVehiclesCount: 25,
  },
  {
    id: "22",
    name: "XRF Spectrum Analysis",
    type: "Refine",
    laborCost: 130,
    linkedVehiclesCount: null,
  },
  {
    id: "23",
    name: "Heat Shield Fastening",
    type: "Mechanical",
    laborCost: 25,
    linkedVehiclesCount: 63,
  },
  {
    id: "24",
    name: "Cold Start Performance Log",
    type: "Inspection",
    laborCost: 75,
    linkedVehiclesCount: null,
  },
  {
    id: "25",
    name: "Manifold Gasket Swap",
    type: "Mechanical",
    laborCost: 115,
    linkedVehiclesCount: 21,
  },
];
